# Generated by Django 5.2.3 on 2025-07-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csbcp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
    ]
